/*
	Middle man with contents are device classes generated by the support module

	TODO: maybe add back to support, index, etc or move one of them? They all cross required each other, that's why I exist
*/
module.exports = {};
